import type { Metadata } from "next";
import './globals.css';

import { Nunito_Sans, Playfair } from 'next/font/google';

import { ProtectedConvexPage } from '@components/layouts/ConvexPage';
import { ProtectedPage } from '@components/layouts/ProtectedPage';
import { NavigationBar } from '@components/shared/NavigationBar/NavigationBar';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body className={"background"}>
        <ProtectedPage>
          <ProtectedConvexPage>
            <main className="background">
              <NavigationBar />
              {children}
            </main>
          </ProtectedConvexPage>
        </ProtectedPage>
      </body>
    </html>
  );
}
