import type { Metadata } from "next";
import './globals.css';

import { Inter } from 'next/font/google';

import { ProtectedConvexPage } from '@components/layouts/ConvexPage';
import { ProtectedPage } from '@components/layouts/ProtectedPage';
import { NavigationBar } from '@components/shared/NavigationBar/NavigationBar';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " background"}>
        <ProtectedPage>
          <ProtectedConvexPage>
            <NavigationBar />
            {children}
          </ProtectedConvexPage>
        </ProtectedPage>
      </body>
    </html>
  );
}
